# Generated by Django 3.2.12 on 2022-02-06 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formtemplate',
            old_name='form_id',
            new_name='form_template_id',
        ),
    ]
