# Generated by Django 3.2.12 on 2022-02-06 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms_app', '0002_rename_form_id_formtemplate_form_template_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormEntry',
            fields=[
                ('form_entry_id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('form_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_entries', to='forms_app.formtemplate')),
            ],
        ),
        migrations.CreateModel(
            name='FormFieldAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=100, null=True)),
                ('form_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_answers', to='forms_app.formentry')),
                ('form_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_field_answers', to='forms_app.formfield')),
            ],
            options={
                'unique_together': {('form_entry', 'form_field')},
            },
        ),
    ]
